# 넘파이 Numpy

## numpy as np

In [1]:
!pip install qrcode

In [13]:
import qrcode
import Pil

def qrcode_maker(text, filename="./qr.png"):
    qr = qrcode.make(text)
    qr.save(filename)

ModuleNotFoundError: No module named 'Pil'

In [14]:
qrcode_maker("안녕하세요. 박형진입니다.")

In [9]:
!pip install Pillow

   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.0 MB ? eta -:--:--
   --- ------------------------------------ 0.5/7.0 MB 976.8 kB/s eta 0:00:07
   --- ------------------------------------ 0.5/7.0 MB 976.8 kB/s eta 0:00:07
   ---- ----------------------------------- 0.8/7.0 MB 687.3 kB/s eta 0:00:10
   ---- ----------------------------------- 0.8/7.0 MB 687.3 kB/s eta 0:00:10
   ------ --------------------------------- 1.0/7.0 MB 700.6 kB/s eta 0:00:09
   ------ --------------------------------- 1.0/7.0 MB 700

In [19]:
# numpy 
import numpy as np

data1 = [1,2,3,4,5]
data2 = [1,2,3,4,5,6]
data1, data2

([1, 2, 3, 4, 5], [1, 2, 3, 4, 5, 6])

In [18]:
arr1 = np.array(data1)
arr2 = np.array(data2)
arr1, arr2

(array([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5, 6]))

In [21]:
arr1. shape , arr1.dtype

((5,), dtype('int64'))

In [26]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:

arr3.shape, arr3.dtype

((2, 3), dtype('int64'))

In [28]:
zz = np.zeros(10)
zz, zz.shape, zz.dtype

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), (10,), dtype('float64'))

In [30]:
zzz = np.zeros((3,5))
zzz, zzz.shape, zzz.dtype

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 (3, 5),
 dtype('float64'))

In [32]:
oo = np.ones(7)
oo, oo.shape, oo.dtype

(array([1., 1., 1., 1., 1., 1., 1.]), (7,), dtype('float64'))

In [34]:
ooo = np.ones((2,10,3))
ooo, ooo.shape, ooo.dtype

(array([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],
 
        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]),
 (2, 10, 3),
 dtype('float64'))

In [35]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(4,12)

array([ 4,  5,  6,  7,  8,  9, 10, 11])

## np.array 연산

In [38]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[10,11,12],[13,14,15]])
arr1, arr2


(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[10, 11, 12],
        [13, 14, 15]]))

In [39]:
print(arr1.shape, arr1.dtype)
print(arr2.shape, arr2.dtype)

(2, 3) int64
(2, 3) int64


In [48]:
result0 = arr1 * 3
result1 = arr1 + arr2
result2 = arr1 - arr2
result3 = arr1 * arr2
result4 = arr1 / arr2
result5 = arr1*2 - arr2/10

print(result0)
print(result1)
print(result2)
print(result3)
print(result4)
print(result5)

[[ 3  6  9]
 [12 15 18]]
[[11 13 15]
 [17 19 21]]
[[-9 -9 -9]
 [-9 -9 -9]]
[[10 22 36]
 [52 70 90]]
[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]]
[[ 1.   2.9  4.8]
 [ 6.7  8.6 10.5]]
