# 넘파이 Numpy

## numpy as np

In [1]:
!pip install qrcode

In [13]:
import qrcode
import Pil

def qrcode_maker(text, filename="./qr.png"):
    qr = qrcode.make(text)
    qr.save(filename)

ModuleNotFoundError: No module named 'Pil'

In [14]:
qrcode_maker("안녕하세요. 박형진입니다.")

In [9]:
!pip install Pillow

   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.0 MB ? eta -:--:--
   --- ------------------------------------ 0.5/7.0 MB 976.8 kB/s eta 0:00:07
   --- ------------------------------------ 0.5/7.0 MB 976.8 kB/s eta 0:00:07
   ---- ----------------------------------- 0.8/7.0 MB 687.3 kB/s eta 0:00:10
   ---- ----------------------------------- 0.8/7.0 MB 687.3 kB/s eta 0:00:10
   ------ --------------------------------- 1.0/7.0 MB 700.6 kB/s eta 0:00:09
   ------ --------------------------------- 1.0/7.0 MB 700

In [19]:
# numpy 
import numpy as np

data1 = [1,2,3,4,5]
data2 = [1,2,3,4,5,6]
data1, data2

([1, 2, 3, 4, 5], [1, 2, 3, 4, 5, 6])

In [18]:
arr1 = np.array(data1)
arr2 = np.array(data2)
arr1, arr2

(array([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5, 6]))

In [21]:
arr1. shape , arr1.dtype

((5,), dtype('int64'))

In [26]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:

arr3.shape, arr3.dtype

((2, 3), dtype('int64'))

In [28]:
zz = np.zeros(10)
zz, zz.shape, zz.dtype

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), (10,), dtype('float64'))

In [30]:
zzz = np.zeros((3,5))
zzz, zzz.shape, zzz.dtype

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 (3, 5),
 dtype('float64'))

In [32]:
oo = np.ones(7)
oo, oo.shape, oo.dtype

(array([1., 1., 1., 1., 1., 1., 1.]), (7,), dtype('float64'))

In [34]:
ooo = np.ones((2,10,3))
ooo, ooo.shape, ooo.dtype

(array([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],
 
        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]),
 (2, 10, 3),
 dtype('float64'))

In [35]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(4,12)

array([ 4,  5,  6,  7,  8,  9, 10, 11])

## np.array 연산

In [38]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[10,11,12],[13,14,15]])
arr1, arr2


(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[10, 11, 12],
        [13, 14, 15]]))

In [39]:
print(arr1.shape, arr1.dtype)
print(arr2.shape, arr2.dtype)

(2, 3) int64
(2, 3) int64


In [48]:
result0 = arr1 * 3
result1 = arr1 + arr2
result2 = arr1 - arr2
result3 = arr1 * arr2
result4 = arr1 / arr2
result5 = arr1*2 - arr2/10

print(result0)
print(result1)
print(result2)
print(result3)
print(result4)
print(result5)

[[ 3  6  9]
 [12 15 18]]
[[11 13 15]
 [17 19 21]]
[[-9 -9 -9]
 [-9 -9 -9]]
[[10 22 36]
 [52 70 90]]
[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]]
[[ 1.   2.9  4.8]
 [ 6.7  8.6 10.5]]


In [50]:
arr3 = np.array([22,33,44])
print(arr1 + arr3)


[[23 35 47]
 [26 38 50]]


## 1차원

In [51]:
# 1차원과 속성들
# shape : 배열의 차원정보
# dtype : 배열 원소의 자료형
# size : 배열의 원소 총 개수
# ndim : 축의 개수

arr = np.arange(5)
arr, arr.shape, arr.dtype, arr.size, arr.ndim

(array([0, 1, 2, 3, 4]), (5,), dtype('int64'), 5, 1)

In [52]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,'a','b'])
arr3 = np.array([1,2,3,4], dtype='str')

print(arr1, arr1.dtype)
print(arr2, arr2.dtype)
print(arr3, arr3.dtype)



[1 2 3 4] int64
['1' '2' 'a' 'b'] <U21
['1' '2' '3' '4'] <U1


In [ ]:
arr5 = np.eye(10)
arr5, arr5.dtype

(array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]]),
 dtype('float64'))

In [63]:
arr6 = np.linspace(0,100,5, endpoint=False, dtype="int64")
print(arr6)
arr7 = np.arange(0,100,20)
print(arr7)


[ 0 20 40 60 80]
[ 0 20 40 60 80]


## 2차원

In [68]:
arr20 = np.array([[1,2],[3,4]])
arr20, arr20.shape, arr20.size, arr20.dtype, arr20.ndim, type(arr20)

(array([[1, 2],
        [3, 4]]),
 (2, 2),
 4,
 dtype('int64'),
 2,
 numpy.ndarray)

In [70]:
arr21 = np.array([[1,2],[3,4]])
arr21 , arr21.shape, arr21.size, arr21.dtype, arr21.ndim, type(arr21)

(array([[1, 2],
        [3, 4]]),
 (2, 2),
 4,
 dtype('int64'),
 2,
 numpy.ndarray)

In [78]:
try:
    arr21 = np.arange(1,10).reshape(3,3)
    print(arr21 , arr21.shape, arr21.size, arr21.dtype, arr21.ndim, type(arr21))
    arr22 = np.arange(1,11).reshape(2,5)
    print(arr22 , arr22.shape, arr22.size, arr22.dtype, arr22.ndim, type(arr22))
    arr23 = np.arange(1,19).reshape(3,6)
    print(arr23 , arr23.shape, arr23.size, arr23.dtype, arr23.ndim, type(arr23))
except ValueError as e:
    print("차원과 사이즈가 맞지 않아요")
    


[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) 9 int64 2 <class 'numpy.ndarray'>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] (2, 5) 10 int64 2 <class 'numpy.ndarray'>
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]] (3, 6) 18 int64 2 <class 'numpy.ndarray'>


In [ ]:
try:
    arr21 = np.arange(1,10).reshape(3,3)
    print(arr21 , arr21.shape, arr21.size, arr21.dtype, arr21.ndim, type(arr21))
    arr22 = np.arange(1,11).reshape(2,5)
    print(arr22 , arr22.shape, arr22.size, arr22.dtype, arr22.ndim, type(arr22))
    arr23 = np.arange(1,19).reshape(3,6)
    print(arr23 , arr23.shape, arr23.size, arr23.dtype, arr23.ndim, type(arr23))
except ValueError as e:
    print("차원과 사이즈가 맞지 않아요")